### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [Shumi999/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by Shumi999** [comment]
Moushumi Ahmed
Australia
Noodles
Puzzle
[comparison.txt](https://github.com/Shumi999/github-for-developers-7/files/29312/comparison.txt)
